name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

#test
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.GPG_JSON_KEY }}

      - name: Install dependencies
        run: |
          if [ -e package-json.lock ]; then
          npm ci
          else
          npm i
          fi
      - name: EAS  updates
        run: npm run update:apk --auto
      - name: Build on EAS
        run: eas build -p android --profile preview
